name: build
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - name: Build VSIX package
        run: |
          npm install -g vsce
          vsce package -o mathpad.vsix

      - name: Upload VSIX package
        uses: actions/upload-artifact@v2
        with:
          name: mathpad-${{ github.sha }}.vsix
          path: mathpad.vsix
